### ISSUE TITLE
Secciones

### ISSUE THREAD

**Issue by MaTiUs77** [MaTiUs77/siep-admin#20]
+ Fix Titulo de secciones (dice instituciones)
+ Fix conteo (dice instituciones)
+ Solo mostrar resultados (con division)

**Comment by deeze307** [comment]
[X] Fix Titulo de secciones (dice instituciones)
[X] Fix conteo (dice instituciones)
[   ] Solo mostrar resultados (con division)

**Comment by deeze307** [comment]
[X] Fix Titulo de secciones (dice instituciones)
[X] Fix conteo (dice instituciones)
[X] Solo mostrar resultados (con division)
