### ISSUE TITLE
Seccion instituciones con Mapa y filtros

### ISSUE THREAD

**Issue by MaTiUs77** [MaTiUs77/siep-admin#37]
Rediseñar sección instituciones
- [X] Agregar mapa interactivo
- [x] Los filtros de busqueda se deben reflejar en el mapa
- [X] Utilizar API de Google Maps
- [x] Modal con datos de Institución
- [x] Oferta académica en Modal de Institución

**Comment by deeze307** [comment]
* [X] Agregar mapa interactivo
 * [X] Los filtros de busqueda se deben reflejar en el mapa
 * [X] Utilizar API de Google Maps
 * [Pendiente] Información de institución al pesionar Marcador en el mapa
